// SPDX-License-Identifier: MIT OR Apache-2.0
// Board presets extracted
use super::{BoardPreset, BoardKind, CpuArch, FlashToolKind};

pub const BOARD_PRESETS: &[BoardPreset] = &[
    BoardPreset {
        kind: BoardKind::ArduinoUno,
        display_name: "Arduino Uno (ATmega328P)",
        cpu_arch: CpuArch::AvrMega,
        target_triple: "avr-unknown-gnu-atmega328",
        avrdude_mcu: Some("m328p"),
        flash_tool: FlashToolKind::Avrdude,
        default_baud: 115200,
        default_port_hint: None,
        usb_ids: super::usb_ids::UNO_USB_IDS,
        toolchain_note: Some("nightly + avr-gcc required"),
    },
    BoardPreset {
        kind: BoardKind::ArduinoNano,
        display_name: "Arduino Nano (ATmega328P)",
        cpu_arch: CpuArch::AvrMega,
        target_triple: "avr-unknown-gnu-atmega328",
        avrdude_mcu: Some("m328p"),
        flash_tool: FlashToolKind::Avrdude,
        default_baud: 57600,
        default_port_hint: None,
        usb_ids: super::usb_ids::NANO_USB_IDS,
        toolchain_note: Some("nightly + avr-gcc required"),
    },
    BoardPreset {
        kind: BoardKind::ArduinoMega,
        display_name: "Arduino Mega 2560 (ATmega2560)",
        cpu_arch: CpuArch::AvrMega,
        target_triple: "avr-unknown-gnu-atmega2560",
        avrdude_mcu: Some("m2560"),
        flash_tool: FlashToolKind::Avrdude,
        default_baud: 115200,
        default_port_hint: None,
        usb_ids: super::usb_ids::MEGA_USB_IDS,
        toolchain_note: Some("nightly + avr-gcc required"),
    },
    BoardPreset {
        kind: BoardKind::ArduinoLeonardo,
        display_name: "Arduino Leonardo (ATmega32u4)",
        cpu_arch: CpuArch::AvrMega,
        target_triple: "avr-unknown-gnu-atmega32u4",
        avrdude_mcu: Some("m32u4"),
        flash_tool: FlashToolKind::Avrdude,
        default_baud: 57600,
        default_port_hint: None,
        usb_ids: super::usb_ids::LEONARDO_USB_IDS,
        toolchain_note: Some("nightly + avr-gcc required"),
    },
    BoardPreset {
        kind: BoardKind::RpiPico,
        display_name: "Raspberry Pi Pico (RP2040, Cortex-M0+)",
        cpu_arch: CpuArch::CortexM0,
        target_triple: "thumbv6m-none-eabi",
        avrdude_mcu: None,
        flash_tool: FlashToolKind::Picotool,
        default_baud: 115200,
        default_port_hint: None,
        usb_ids: super::usb_ids::RPI_PICO_USB_IDS,
        toolchain_note: None,
    },
    BoardPreset {
        kind: BoardKind::Esp32,
        display_name: "ESP32 (Xtensa LX6)",
        cpu_arch: CpuArch::XtensaLx6,
        target_triple: "xtensa-esp32-none-elf",
        avrdude_mcu: None,
        flash_tool: FlashToolKind::Esptool,
        default_baud: 115200,
        default_port_hint: None,
        usb_ids: super::usb_ids::ESP32_USB_IDS,
        toolchain_note: Some("espup install required: cargo install espup && espup install"),
    },
];
