[package]
name = "blink"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "blink"
test = false
bench = false

[dependencies]
stm32f4xx-hal = { version = "0.21", features = ["stm32f401"] }
cortex-m-rt = "0.7"
cortex-m = "0.7"
panic-halt = "0.2"

[profile.dev]
panic = "abort"
lto = true
opt-level = "s"

[profile.release]
lto = true
opt-level = "s"
